[workspace]
resolver = "2"
members = [
    "basics",
    "clus",
    "cmd",
    "hello-rust",
    "use-mod",
    "quick-replace",
    "mandelbrot",
    "seesaw",
    "web-with-prometheus",
    "api",
]
