[workspace]
resolver = "2"
members = [
    "api",
    "basics",
    "clus",
    "cmd",
    "hello-rust",
    "hv",
    "mandelbrot",
    "OTel",
    "quick-replace",
    "seesaw",
    "use-mod",
    "web-with-prometheus",
]
